use_frameworks!

platform :ios, '8.0'

target 'TestFoundation_Example' do
  pod 'TestFoundation', :path => '../'

  target 'TestFoundation_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
